# Generated by Django 5.1 on 2024-08-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cover_alter_recipe_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Author',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=165),
        ),
    ]
